# Generated by Django 5.0.6 on 2024-06-14 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('passport_number', models.CharField(max_length=15, verbose_name='Номер паспорта')),
                ('place_of_birth', models.CharField(max_length=255, verbose_name='Место рождения')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Введите правильный российский номер телефона.', regex='^7[0-9]{10}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('registration_address', models.CharField(max_length=255, verbose_name='Адрес регистрации')),
                ('residential_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес проживания')),
            ],
        ),
    ]
